before_script:
  - psql -c 'create database sqlalchemy_searchable_test;' -U postgres

language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -e ".[test]"
script:
  - py.test
