before_script:
  - psql -c 'create database sqlalchemy_searchable_test;' -U postgres

language: python
python:
  - 2.5
  - 2.6
  - 2.7
install:
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
